name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &

    - name: Run build
      run: npm run build

    - name: Stop application
      run: kill $(lsof -t -i:3000) || echo "Process not found"
